// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/sync/sync.proto

package sync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncAction_ActionType int32

const (
	SyncAction_DOWNLOAD SyncAction_ActionType = 0
	SyncAction_UPLOAD   SyncAction_ActionType = 1
	SyncAction_DELETE   SyncAction_ActionType = 2
)

// Enum value maps for SyncAction_ActionType.
var (
	SyncAction_ActionType_name = map[int32]string{
		0: "DOWNLOAD",
		1: "UPLOAD",
		2: "DELETE",
	}
	SyncAction_ActionType_value = map[string]int32{
		"DOWNLOAD": 0,
		"UPLOAD":   1,
		"DELETE":   2,
	}
)

func (x SyncAction_ActionType) Enum() *SyncAction_ActionType {
	p := new(SyncAction_ActionType)
	*p = x
	return p
}

func (x SyncAction_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncAction_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sync_sync_proto_enumTypes[0].Descriptor()
}

func (SyncAction_ActionType) Type() protoreflect.EnumType {
	return &file_proto_sync_sync_proto_enumTypes[0]
}

func (x SyncAction_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncAction_ActionType.Descriptor instead.
func (SyncAction_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_sync_sync_proto_rawDescGZIP(), []int{4, 0}
}

type FileState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileState) Reset() {
	*x = FileState{}
	mi := &file_proto_sync_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileState) ProtoMessage() {}

func (x *FileState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileState.ProtoReflect.Descriptor instead.
func (*FileState) Descriptor() ([]byte, []int) {
	return file_proto_sync_sync_proto_rawDescGZIP(), []int{0}
}

func (x *FileState) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileState) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileState) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type RegisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_proto_sync_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_sync_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterDeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResponse) Reset() {
	*x = RegisterDeviceResponse{}
	mi := &file_proto_sync_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponse) ProtoMessage() {}

func (x *RegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_sync_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterDeviceResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterDeviceResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetSyncPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalFiles    []*FileState           `protobuf:"bytes,1,rep,name=local_files,json=localFiles,proto3" json:"local_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncPlanRequest) Reset() {
	*x = GetSyncPlanRequest{}
	mi := &file_proto_sync_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncPlanRequest) ProtoMessage() {}

func (x *GetSyncPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncPlanRequest.ProtoReflect.Descriptor instead.
func (*GetSyncPlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_sync_proto_rawDescGZIP(), []int{3}
}

func (x *GetSyncPlanRequest) GetLocalFiles() []*FileState {
	if x != nil {
		return x.LocalFiles
	}
	return nil
}

type SyncAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Action        SyncAction_ActionType  `protobuf:"varint,2,opt,name=action,proto3,enum=sync.SyncAction_ActionType" json:"action,omitempty"`
	VersionId     string                 `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAction) Reset() {
	*x = SyncAction{}
	mi := &file_proto_sync_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAction) ProtoMessage() {}

func (x *SyncAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAction.ProtoReflect.Descriptor instead.
func (*SyncAction) Descriptor() ([]byte, []int) {
	return file_proto_sync_sync_proto_rawDescGZIP(), []int{4}
}

func (x *SyncAction) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SyncAction) GetAction() SyncAction_ActionType {
	if x != nil {
		return x.Action
	}
	return SyncAction_DOWNLOAD
}

func (x *SyncAction) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *SyncAction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SyncAction) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetSyncPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*SyncAction          `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncPlanResponse) Reset() {
	*x = GetSyncPlanResponse{}
	mi := &file_proto_sync_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncPlanResponse) ProtoMessage() {}

func (x *GetSyncPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncPlanResponse.ProtoReflect.Descriptor instead.
func (*GetSyncPlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_sync_proto_rawDescGZIP(), []int{5}
}

func (x *GetSyncPlanResponse) GetActions() []*SyncAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadFileRequest_Meta
	//	*UploadFileRequest_Data
	Payload       isUploadFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_proto_sync_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_sync_proto_rawDescGZIP(), []int{6}
}

func (x *UploadFileRequest) GetPayload() isUploadFileRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadFileRequest) GetMeta() *UploadFileMeta {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileRequest_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *UploadFileRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUploadFileRequest_Payload interface {
	isUploadFileRequest_Payload()
}

type UploadFileRequest_Meta struct {
	Meta *UploadFileMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type UploadFileRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UploadFileRequest_Meta) isUploadFileRequest_Payload() {}

func (*UploadFileRequest_Data) isUploadFileRequest_Payload() {}

type UploadFileMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	BaseVersionId string                 `protobuf:"bytes,2,opt,name=base_version_id,json=baseVersionId,proto3" json:"base_version_id,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileMeta) Reset() {
	*x = UploadFileMeta{}
	mi := &file_proto_sync_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileMeta) ProtoMessage() {}

func (x *UploadFileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileMeta.ProtoReflect.Descriptor instead.
func (*UploadFileMeta) Descriptor() ([]byte, []int) {
	return file_proto_sync_sync_proto_rawDescGZIP(), []int{7}
}

func (x *UploadFileMeta) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadFileMeta) GetBaseVersionId() string {
	if x != nil {
		return x.BaseVersionId
	}
	return ""
}

func (x *UploadFileMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadFileMeta) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	NewVersionId  string                 `protobuf:"bytes,2,opt,name=new_version_id,json=newVersionId,proto3" json:"new_version_id,omitempty"`
	Conflict      bool                   `protobuf:"varint,3,opt,name=conflict,proto3" json:"conflict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_proto_sync_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_sync_proto_rawDescGZIP(), []int{8}
}

func (x *UploadFileResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UploadFileResponse) GetNewVersionId() string {
	if x != nil {
		return x.NewVersionId
	}
	return ""
}

func (x *UploadFileResponse) GetConflict() bool {
	if x != nil {
		return x.Conflict
	}
	return false
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_proto_sync_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_sync_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DownloadFileResponse_Meta
	//	*DownloadFileResponse_Data
	Payload       isDownloadFileResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_proto_sync_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_sync_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadFileResponse) GetPayload() isDownloadFileResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DownloadFileResponse) GetMeta() *DownloadFileMeta {
	if x != nil {
		if x, ok := x.Payload.(*DownloadFileResponse_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *DownloadFileResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*DownloadFileResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isDownloadFileResponse_Payload interface {
	isDownloadFileResponse_Payload()
}

type DownloadFileResponse_Meta struct {
	Meta *DownloadFileMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type DownloadFileResponse_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*DownloadFileResponse_Meta) isDownloadFileResponse_Payload() {}

func (*DownloadFileResponse_Data) isDownloadFileResponse_Payload() {}

type DownloadFileMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileMeta) Reset() {
	*x = DownloadFileMeta{}
	mi := &file_proto_sync_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileMeta) ProtoMessage() {}

func (x *DownloadFileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileMeta.ProtoReflect.Descriptor instead.
func (*DownloadFileMeta) Descriptor() ([]byte, []int) {
	return file_proto_sync_sync_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadFileMeta) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DownloadFileMeta) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *DownloadFileMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DownloadFileMeta) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_proto_sync_sync_proto protoreflect.FileDescriptor

const file_proto_sync_sync_proto_rawDesc = "" +
	"\n" +
	"\x15proto/sync/sync.proto\x12\x04sync\"G\n" +
	"\tFileState\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\"+\n" +
	"\x15RegisterDeviceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x16RegisterDeviceResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"F\n" +
	"\x12GetSyncPlanRequest\x120\n" +
	"\vlocal_files\x18\x01 \x03(\v2\x0f.sync.FileStateR\n" +
	"localFiles\"\xd0\x01\n" +
	"\n" +
	"SyncAction\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x123\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1b.sync.SyncAction.ActionTypeR\x06action\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\tR\tversionId\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\"2\n" +
	"\n" +
	"ActionType\x12\f\n" +
	"\bDOWNLOAD\x10\x00\x12\n" +
	"\n" +
	"\x06UPLOAD\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\"A\n" +
	"\x13GetSyncPlanResponse\x12*\n" +
	"\aactions\x18\x01 \x03(\v2\x10.sync.SyncActionR\aactions\"`\n" +
	"\x11UploadFileRequest\x12*\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.sync.UploadFileMetaH\x00R\x04meta\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"t\n" +
	"\x0eUploadFileMeta\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12&\n" +
	"\x0fbase_version_id\x18\x02 \x01(\tR\rbaseVersionId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\"r\n" +
	"\x12UploadFileResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12$\n" +
	"\x0enew_version_id\x18\x02 \x01(\tR\fnewVersionId\x12\x1a\n" +
	"\bconflict\x18\x03 \x01(\bR\bconflict\")\n" +
	"\x13DownloadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"e\n" +
	"\x14DownloadFileResponse\x12,\n" +
	"\x04meta\x18\x01 \x01(\v2\x16.sync.DownloadFileMetaH\x00R\x04meta\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"m\n" +
	"\x10DownloadFileMeta\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash2\xaa\x02\n" +
	"\vSyncService\x12K\n" +
	"\x0eRegisterDevice\x12\x1b.sync.RegisterDeviceRequest\x1a\x1c.sync.RegisterDeviceResponse\x12B\n" +
	"\vGetSyncPlan\x12\x18.sync.GetSyncPlanRequest\x1a\x19.sync.GetSyncPlanResponse\x12A\n" +
	"\n" +
	"UploadFile\x12\x17.sync.UploadFileRequest\x1a\x18.sync.UploadFileResponse(\x01\x12G\n" +
	"\fDownloadFile\x12\x19.sync.DownloadFileRequest\x1a\x1a.sync.DownloadFileResponse0\x01B.Z,github.com/shivangnagta/data_sync/proto/syncb\x06proto3"

var (
	file_proto_sync_sync_proto_rawDescOnce sync.Once
	file_proto_sync_sync_proto_rawDescData []byte
)

func file_proto_sync_sync_proto_rawDescGZIP() []byte {
	file_proto_sync_sync_proto_rawDescOnce.Do(func() {
		file_proto_sync_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sync_sync_proto_rawDesc), len(file_proto_sync_sync_proto_rawDesc)))
	})
	return file_proto_sync_sync_proto_rawDescData
}

var file_proto_sync_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_sync_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_sync_sync_proto_goTypes = []any{
	(SyncAction_ActionType)(0),     // 0: sync.SyncAction.ActionType
	(*FileState)(nil),              // 1: sync.FileState
	(*RegisterDeviceRequest)(nil),  // 2: sync.RegisterDeviceRequest
	(*RegisterDeviceResponse)(nil), // 3: sync.RegisterDeviceResponse
	(*GetSyncPlanRequest)(nil),     // 4: sync.GetSyncPlanRequest
	(*SyncAction)(nil),             // 5: sync.SyncAction
	(*GetSyncPlanResponse)(nil),    // 6: sync.GetSyncPlanResponse
	(*UploadFileRequest)(nil),      // 7: sync.UploadFileRequest
	(*UploadFileMeta)(nil),         // 8: sync.UploadFileMeta
	(*UploadFileResponse)(nil),     // 9: sync.UploadFileResponse
	(*DownloadFileRequest)(nil),    // 10: sync.DownloadFileRequest
	(*DownloadFileResponse)(nil),   // 11: sync.DownloadFileResponse
	(*DownloadFileMeta)(nil),       // 12: sync.DownloadFileMeta
}
var file_proto_sync_sync_proto_depIdxs = []int32{
	1,  // 0: sync.GetSyncPlanRequest.local_files:type_name -> sync.FileState
	0,  // 1: sync.SyncAction.action:type_name -> sync.SyncAction.ActionType
	5,  // 2: sync.GetSyncPlanResponse.actions:type_name -> sync.SyncAction
	8,  // 3: sync.UploadFileRequest.meta:type_name -> sync.UploadFileMeta
	12, // 4: sync.DownloadFileResponse.meta:type_name -> sync.DownloadFileMeta
	2,  // 5: sync.SyncService.RegisterDevice:input_type -> sync.RegisterDeviceRequest
	4,  // 6: sync.SyncService.GetSyncPlan:input_type -> sync.GetSyncPlanRequest
	7,  // 7: sync.SyncService.UploadFile:input_type -> sync.UploadFileRequest
	10, // 8: sync.SyncService.DownloadFile:input_type -> sync.DownloadFileRequest
	3,  // 9: sync.SyncService.RegisterDevice:output_type -> sync.RegisterDeviceResponse
	6,  // 10: sync.SyncService.GetSyncPlan:output_type -> sync.GetSyncPlanResponse
	9,  // 11: sync.SyncService.UploadFile:output_type -> sync.UploadFileResponse
	11, // 12: sync.SyncService.DownloadFile:output_type -> sync.DownloadFileResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_sync_sync_proto_init() }
func file_proto_sync_sync_proto_init() {
	if File_proto_sync_sync_proto != nil {
		return
	}
	file_proto_sync_sync_proto_msgTypes[6].OneofWrappers = []any{
		(*UploadFileRequest_Meta)(nil),
		(*UploadFileRequest_Data)(nil),
	}
	file_proto_sync_sync_proto_msgTypes[10].OneofWrappers = []any{
		(*DownloadFileResponse_Meta)(nil),
		(*DownloadFileResponse_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sync_sync_proto_rawDesc), len(file_proto_sync_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sync_sync_proto_goTypes,
		DependencyIndexes: file_proto_sync_sync_proto_depIdxs,
		EnumInfos:         file_proto_sync_sync_proto_enumTypes,
		MessageInfos:      file_proto_sync_sync_proto_msgTypes,
	}.Build()
	File_proto_sync_sync_proto = out.File
	file_proto_sync_sync_proto_goTypes = nil
	file_proto_sync_sync_proto_depIdxs = nil
}
